### ISSUE TITLE
接口服务

### ISSUE THREAD

**Issue by baogutang** [sooooooooooooooooootheby/Netease_analyze#1]
您好~请问接口服务有么~

**Comment by meorionel** [comment]
> 您好~请问接口服务有么~

看api部分

https://blog.sooooooooooooooooootheby.top/

**Comment by baogutang** [comment]
大佬，博客停站了妈

**Comment by meorionel** [comment]
> 大佬，博客停站了妈

换域名了 博客新域名是blog.s22y.moe

api的话看 https://s22y.moe/api.html 但是我nginx没配置好 docs 有点问题
