### ISSUE TITLE
单曲模式报错，功能异常

### ISSUE THREAD

**Issue by hexi618** [sooooooooooooooooootheby/Netease_analyze#2]
https://music.sooooooooooooooooootheby.top/

这个页面中，TAB控件选“单曲模式”，下方输入歌曲地址“https://music.163.com/song?id=27698847”，音质选“超清母带”；最后点击按钮“获取歌曲”，页面右侧提示错误“请输入正确的歌单链接或id”。

（另，当选择歌单模式，通过歌单id，可顺利解析出歌单内的歌曲，并可进一步完成选择下载）

**Comment by meorionel** [comment]
“请输入正确的歌单链接或id”的问题修好了, 但是你这首歌网易云那边没版权听不了, 所以我用单曲模式解析不出来。

另外你说歌单模式能够解析下载，但是我具体测试了一下也是下载不了的。

**Comment by hexi618** [comment]
谢谢回复。
应该是我对问题的描述不够精确，没有版权的歌曲是下载不了的，这个是客观局限。
单曲模式刚刚重新试用了下，可以顺利解析到内容，并且也成功下载到文件了。
-----------------

歌单模式可用，可以解析出歌单内的歌曲，但是使用中又发现存在两种异常：

1、有些歌它总是提示错误信息
（目前有部分音乐无法正常解析, 需要等Api作者回复才有具体解决方法.获取歌曲失败: AxiosError: Request failed with status code 500）
具体的操作中，我每次选中10首歌，然后点击“下载已选”，此时页面右侧就会出现一两个，有时是两三个相同的报错提示。最后得到的打包文件中，相应的会缺少一两首歌。
这个故障如果可以在报错提示中显示具体出错歌曲的名称，对使用排查也有一定的帮助。
另外，这个故障似乎不是因为歌曲本身不支持下载引起的，比如同样的歌曲（https://music.163.com/song?id=1347995196），在提示出错，且下载后的zip文件中没有这首歌后，将歌曲地址放在 @苏晓晴 的单曲解析页面中，可以顺利下载到文件包。

2、歌单模式下载功能使用中，第一次选中 A1 ~A10 共10首歌，得到 songs.zip 文件。第二次选中 B1 ~ B10 共10首歌，得到的 songs.zip 文件中，它体积非常大，解压后才发现，它里面包含着 A1 ~ A10 的歌曲文件。前提：确认确定第二次只选中了 B1 ~ B10。
刚刚我还进行了第三次，选择了 C1 ~ C10 共10首歌曲，但它页面上的进度条达到 100%后，一直滞留无反应，顺利的话，浏览器右下角下载管理图标处，应该出现有压缩文件包正在载入本地，但是并没有，猜测它可能正在将我前两次下载的歌曲叠加打包……这个打包时长的确有些久，尤其是它没有任何进度提示的前提下。事实上，之所以用“每次只选10首来下载，也是因为第一次是全选下载70首歌，结果在等待打包这个环节，等太久，并不知道它是不是卡死掉了，无奈放弃，刷新页面重新操作……”

最后谢谢你制作的这个工具，打包下载帮我节省了不少时间。再次感谢。


附上几例“下载时报错，但可以在 @苏晓晴 页面中完成下载的歌曲，便于你排查异常
https://music.163.com/song?id=1934003072
https://music.163.com/song?id=1347995196
https://music.163.com/song?id=5147563

**Comment by meorionel** [comment]
> ## 谢谢回复。
> 应该是我对问题的描述不够精确，没有版权的歌曲是下载不了的，这个是客观局限。
> 单曲模式刚刚重新试用了下，可以顺利解析到内容，并且也成功下载到文件了。
> 歌单模式可用，可以解析出歌单内的歌曲，但是使用中又发现存在两种异常：
> 
> 1、有些歌它总是提示错误信息 （目前有部分音乐无法正常解析, 需要等Api作者回复才有具体解决方法.获取歌曲失败: AxiosError: Request failed with status code 500） 具体的操作中，我每次选中10首歌，然后点击“下载已选”，此时页面右侧就会出现一两个，有时是两三个相同的报错提示。最后得到的打包文件中，相应的会缺少一两首歌。 这个故障如果可以在报错提示中显示具体出错歌曲的名称，对使用排查也有一定的帮助。 另外，这个故障似乎不是因为歌曲本身不支持下载引起的，比如同样的歌曲（[https://music.163.com/song?id=1347995196），在提示出错，且下载后的zip文件中没有这首歌后，将歌曲地址放在](https://music.163.com/song?id=1347995196%EF%BC%89%EF%BC%8C%E5%9C%A8%E6%8F%90%E7%A4%BA%E5%87%BA%E9%94%99%EF%BC%8C%E4%B8%94%E4%B8%8B%E8%BD%BD%E5%90%8E%E7%9A%84zip%E6%96%87%E4%BB%B6%E4%B8%AD%E6%B2%A1%E6%9C%89%E8%BF%99%E9%A6%96%E6%AD%8C%E5%90%8E%EF%BC%8C%E5%B0%86%E6%AD%8C%E6%9B%B2%E5%9C%B0%E5%9D%80%E6%94%BE%E5%9C%A8) @苏晓晴 的单曲解析页面中，可以顺利下载到文件包。
> 
> 2、歌单模式下载功能使用中，第一次选中 A1 ~A10 共10首歌，得到 songs.zip 文件。第二次选中 B1 ~ B10 共10首歌，得到的 songs.zip 文件中，它体积非常大，解压后才发现，它里面包含着 A1 ~ A10 的歌曲文件。前提：确认确定第二次只选中了 B1 ~ B10。 刚刚我还进行了第三次，选择了 C1 ~ C10 共10首歌曲，但它页面上的进度条达到 100%后，一直滞留无反应，顺利的话，浏览器右下角下载管理图标处，应该出现有压缩文件包正在载入本地，但是并没有，猜测它可能正在将我前两次下载的歌曲叠加打包……这个打包时长的确有些久，尤其是它没有任何进度提示的前提下。事实上，之所以用“每次只选10首来下载，也是因为第一次是全选下载70首歌，结果在等待打包这个环节，等太久，并不知道它是不是卡死掉了，无奈放弃，刷新页面重新操作……”
> 
> 最后谢谢你制作的这个工具，打包下载帮我节省了不少时间。再次感谢。
> 
> 附上几例“下载时报错，但可以在 @苏晓晴 页面中完成下载的歌曲，便于你排查异常 https://music.163.com/song?id=1934003072 https://music.163.com/song?id=1347995196 https://music.163.com/song?id=5147563

苏晓晴那个站点我也拿过去测试了一下，确实是有这个问题，我看了一下姑且是认为她的api和我的api不是同一个api，或者说她站点的api是更新的但是没有推到github上。

我这里看了一下返回的数据 结构是不同的。
![image](https://github.com/user-attachments/assets/fc8ad076-26f8-4e84-9553-b98f9cce5066)

跑到100%卡死的问题是因为打包下载的音乐太大了，导致浏览器分配的内存爆了，我现在已经在解决这个问题了。

**Comment by meorionel** [comment]
> ## 谢谢回复。
> 应该是我对问题的描述不够精确，没有版权的歌曲是下载不了的，这个是客观局限。
> 单曲模式刚刚重新试用了下，可以顺利解析到内容，并且也成功下载到文件了。
> 歌单模式可用，可以解析出歌单内的歌曲，但是使用中又发现存在两种异常：
> 
> 1、有些歌它总是提示错误信息 （目前有部分音乐无法正常解析, 需要等Api作者回复才有具体解决方法.获取歌曲失败: AxiosError: Request failed with status code 500） 具体的操作中，我每次选中10首歌，然后点击“下载已选”，此时页面右侧就会出现一两个，有时是两三个相同的报错提示。最后得到的打包文件中，相应的会缺少一两首歌。 这个故障如果可以在报错提示中显示具体出错歌曲的名称，对使用排查也有一定的帮助。 另外，这个故障似乎不是因为歌曲本身不支持下载引起的，比如同样的歌曲（[https://music.163.com/song?id=1347995196），在提示出错，且下载后的zip文件中没有这首歌后，将歌曲地址放在](https://music.163.com/song?id=1347995196%EF%BC%89%EF%BC%8C%E5%9C%A8%E6%8F%90%E7%A4%BA%E5%87%BA%E9%94%99%EF%BC%8C%E4%B8%94%E4%B8%8B%E8%BD%BD%E5%90%8E%E7%9A%84zip%E6%96%87%E4%BB%B6%E4%B8%AD%E6%B2%A1%E6%9C%89%E8%BF%99%E9%A6%96%E6%AD%8C%E5%90%8E%EF%BC%8C%E5%B0%86%E6%AD%8C%E6%9B%B2%E5%9C%B0%E5%9D%80%E6%94%BE%E5%9C%A8) @苏晓晴 的单曲解析页面中，可以顺利下载到文件包。
> 
> 2、歌单模式下载功能使用中，第一次选中 A1 ~A10 共10首歌，得到 songs.zip 文件。第二次选中 B1 ~ B10 共10首歌，得到的 songs.zip 文件中，它体积非常大，解压后才发现，它里面包含着 A1 ~ A10 的歌曲文件。前提：确认确定第二次只选中了 B1 ~ B10。 刚刚我还进行了第三次，选择了 C1 ~ C10 共10首歌曲，但它页面上的进度条达到 100%后，一直滞留无反应，顺利的话，浏览器右下角下载管理图标处，应该出现有压缩文件包正在载入本地，但是并没有，猜测它可能正在将我前两次下载的歌曲叠加打包……这个打包时长的确有些久，尤其是它没有任何进度提示的前提下。事实上，之所以用“每次只选10首来下载，也是因为第一次是全选下载70首歌，结果在等待打包这个环节，等太久，并不知道它是不是卡死掉了，无奈放弃，刷新页面重新操作……”
> 
> 最后谢谢你制作的这个工具，打包下载帮我节省了不少时间。再次感谢。
> 
> 附上几例“下载时报错，但可以在 @苏晓晴 页面中完成下载的歌曲，便于你排查异常 https://music.163.com/song?id=1934003072 https://music.163.com/song?id=1347995196 https://music.163.com/song?id=5147563

昨天苏晓晴已经把bug都修好了 现在已经没有无法下载的问题了（至少我测试的几首歌都能正常下载了）。

关于进度条，这个进度条我一直没什么好的方案去做，因为比较麻烦 他下载完成后进度条会清空再重新显示打包的进度，我没做好反馈，所以会有一种奇怪的感觉。

还有重复下载的问题我也已经修好了
